---

  - name: Get security keys
    command: scp -o StrictHostKeyChecking=no mapr@{{ primary_host }}:security_keys/{{ item.file }} /opt/mapr/conf/
    register: return_value
    until: return_value|success
    retries: 50
    delay: 10
    with_items:
      - { file: maprserverticket, security: [ kerberos, maprsasl ] }
      - { file: ssl_keystore,     security: [ kerberos, maprsasl ] }
      - { file: ssl_truststore,   security: [ kerberos, maprsasl ] }
      - { file: mapr.keytab,      security: [ kerberos ]           }
    when: (security in item.security)

  - name: Change owner and permissions for security keys
    file: path=/opt/mapr/conf/{{ item.file }} owner=mapr group=mapr mode={{ item.mode }}
    with_items:
      - { file: maprserverticket, mode: 600, security: [ kerberos, maprsasl ] }
      - { file: ssl_keystore,     mode: 400, security: [ kerberos, maprsasl ] }
      - { file: ssl_truststore,   mode: 444, security: [ kerberos, maprsasl ] }
      - { file: mapr.keytab,      mode: 600, security: [ kerberos ]           }
    when: (security in item.security)

#**********************************************************************************************************************

  - name: Run configure.sh (simple)
    command: >
      /opt/mapr/server/configure.sh
      -c
      -C {{ packages_core.cldb.host|first_host|pick(fqdns) }}:7222
      -N {{ cluster_name }}
      -HS {{ packages_core.historyserver.host|first_host|pick(fqdns) }}
    when: (security == "none")

  - name: Run configre.sh (secure)
    command: >
      /opt/mapr/server/configure.sh
      -c
      -C {{ packages_core.cldb.host|first_host|pick(fqdns) }}:7222
      -N {{ cluster_name }}
      -HS {{ packages_core.historyserver.host|first_host|pick(fqdns) }}
      -secure
    when: (security == "maprsasl")

  - name: Run configre.sh (secure)
    command: >
      /opt/mapr/server/configure.sh
      -c
      -C {{ packages_core.cldb.host|first_host|pick(fqdns) }}:7222
      -N {{ cluster_name }}
      -HS {{ packages_core.historyserver.host|first_host|pick(fqdns) }}
      -secure
      -kerberosEnable
      -P {{ mapr_cluster_name_principal }}
    when: (security == "kerberos")
