---

- name: Install the MapR package key
  apt_key: url=http://package.mapr.com/releases/pub/maprgpg.key state=present
  when: (ansible_os_family == 'Debian')

- name: Add MapR Core repo
  apt_repository: repo='{{mapr_core_repo}}' state=present
  when: (ansible_os_family == 'Debian')

- name: Add MapR Ecosystem repo
  apt_repository: repo='{{mapr_eco_repo}}' state=present
  when: (ansible_os_family == 'Debian')

- name: Add MapR Patch repo
  apt_repository: repo='{{mapr_patch_repo}}' state=present
  when: (ansible_os_family == 'Debian') and use_core_patch

#----------------------------------------------------------

- name: Install the MapR package key
  command: rpm --import http://package.mapr.com/releases/pub/maprgpg.key
  when: (ansible_os_family == 'RedHat')

- name: Add MapR Core and Ecosystem hrepo
  template: src=maprtech.repo.j2 dest=/etc/yum.repos.d/maprtech.repo
  when: (ansible_os_family == 'RedHat')

- name: Add MapR Patch repo
  template: src=maprpatch.repo.j2 dest=/etc/yum.repos.d/maprpatch.repo
  when: (ansible_os_family == 'RedHat') and use_core_patch

#----------------------------------------------------------

- name: Install the MapR package key
  command: rpm --import http://package.mapr.com/releases/pub/maprgpg.key
  when: (ansible_os_family == 'Suse')

- name: Add MapR Core and Ecosystem repo
  template: src=maprtech.repo.j2 dest=/etc/zypp/repos.d/maprtech.repo
  when: (ansible_os_family == 'Suse')

- name: Add MapR Patch repo
  template: src=maprpatch.repo.j2 dest=/etc/zypp/repos.d/maprpatch.repo
  when: (ansible_os_family == 'Suse' and use_core_patch)
