---
# ********************
# *** YARN section ***
# ********************

- name: Find YARN config dir
  shell: ls -d /opt/mapr/hadoop/hadoop-*/etc/hadoop
  register: yarn_conf_dir

- name: Copy core-site.xml
  template: src=yarn/core-site.xml.{{ security }} dest={{ yarn_conf_dir.stdout }}/core-site.xml
