---
# ********************
# *** HIVE section ***
# ********************

- name: Find Hive dir
  shell: ls -d /opt/mapr/hive/hive-*
  register: hive_dir

- name: Copy hive-site.xml
  template: src=hive/hive-site.xml.{{security}} dest={{ hive_dir.stdout }}/conf/hive-site.xml

