---
# ********************
# *** Hive section ***
# ********************
- name: Clone tests
  shell: git clone -b hive-mep7-master --depth 1 --single-branch https://6936784d69eb813cbcdf18ed2554e174f6f974ce@github.com/mapr/private-qa.git /home/mapr/private-qa
  become: true
  become_user: mapr

- name: Configure Hive
  include: configure_hive.yml
  when: (hostname in packages_eco.hive.host)

- name: Configure hive-tests
  shell: cd /home/mapr/private-qa/new-ats/eco/hive && bash configure.sh
  sudo: yes
