apiVersion: batch/v1
kind: Job
metadata:
  name: init-mappings
spec:
  template:
    spec:
      containers:
      - name: init-mappings
        image: diptan/elasticsearch-mapping-init
      restartPolicy: Never
  backoffLimit: 2
