apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      # Utilize Init containers to set ulimit, vm-max-map-count, and volume permissions
      initContainers: 
      - name: volume-permission
        image: busybox
        command:
        - sh
        - -c
        - chown -R 1000:1000 /usr/share/elasticsearch/data
        securityContext:
          privileged: true
        volumeMounts:
        - name: es-storage
          mountPath: /usr/share/elasticsearch/data
      containers:
      - env:
        - name: discovery.type
          value: single-node
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
        name: elasticsearch
        ports:
        - containerPort: 9200
        volumeMounts:
        - name: es-storage
          mountPath: "/usr/share/elasticsearch/data"
      volumes:
       - name: es-storage
         persistentVolumeClaim:
           claimName: es-pvc 
      restartPolicy: Always
---
  apiVersion: v1
  kind: Service
  metadata:
    name: elasticsearch
  spec:
    ports:
    - port: 9200
      targetPort: 9200
    selector:
      name: elasticsearch
  