apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsscollector
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rsscollector
  template:
    metadata:
      labels:
        name: rsscollector
    spec:
      containers:
      - image: diptan/rsscollector
        name: rsscollector
      restartPolicy: Always
