apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: streamer
  name: streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: streamer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: streamer
    spec:
      restartPolicy: Always
      containers:
      - image: diptan/streamer:latest
        name: streamer
        volumeMounts:
          - mountPath: /model
            name: csi
      volumes:
        - name: csi
          persistentVolumeClaim:
            claimName: mapr-ro-pvc
