apiVersion: v1
kind: Pod
metadata:
  labels:
    name: trainer
  name: trainer
spec:
  # securityContext:
  #   runAsUser: 5000
  #   fsGroup: 5000
  containers:
    - name: trainer
      image: diptan/trainer:latest
      resources:
        requests:
          memory: "2Gi"
          cpu: "5000m"
      volumeMounts:
        - mountPath: /model
          name: csi
      ports:
        - containerPort: 8081
  volumes:
    - name: csi
      persistentVolumeClaim:
        claimName: model-rw-pvc