apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: trainer
  name: trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: trainer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: trainer
    spec:
      restartPolicy: Always
      containers:
        - name: trainer
          image: diptan/trainer:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /model
              name: csi
          ports:
            - containerPort: 8081
      volumes:
        - name: csi
          persistentVolumeClaim:
            claimName: trainer-rw-pvc
---
  apiVersion: v1
  kind: Service
  metadata:
    name: trainer
  spec:
    ports:
    - port: 8081
      targetPort: 8081
    selector:
      name: trainer
