---

  ################################
  ### Set package_version fact ###
  ################################
- name: "Set package_version with dpkg-query [Debian]"
  set_fact:
    package_version: "dpkg-query --showformat='${Version}' --show"
  when: ansible_os_family in ['Debian']

- name: "Set package_version with rpm [RedHat/Suse]"
  set_fact:
    package_version: "rpm --queryformat='%{VERSION}' -qa"
  when: ansible_os_family in ['RedHat', 'Suse']

  #######################
  ### Clean repo data ###
  #######################
- name: "Update APT cache [Debian]"
  apt: update_cache=yes
  ignore_errors: true
  when: ansible_os_family == 'Debian'

- name: "Update YUM cache [RedHat]"
  command: yum clean all
  ignore_errors: true
  when: ansible_os_family == 'RedHat'

- name: "Update Zypper cache [Suse]"
  command: zypper refresh
  ignore_errors: true
  when: ansible_os_family == 'Suse'

  ####################
  ### Install Java ###
  ####################
- name: "Add repository with Java 8 for Ubuntu 14.04 and Java 11 for Ubuntu 16.04 [Debian]"
  apt_repository: repo='ppa:openjdk-r/ppa' update_cache=yes
  when: ansible_os_family == 'Debian'

- name: "Install Java package"
  package: name={{ packages[ansible_os_family][java_version] }}
  vars:
    packages:
      Debian:
        openjdk7: openjdk-7-jdk
        openjdk8: openjdk-8-jdk
        openjdk11: openjdk-11-jdk
      RedHat:
        openjdk7: java-1.7.0-openjdk-devel
        openjdk8: java-1.8.0-openjdk-devel
        openjdk11: java-11-openjdk-devel
      Suse:
        openjdk7: java-1_7_0-openjdk-devel
        openjdk8: java-1_8_0-openjdk-devel
        openjdk11: java-11-openjdk-devel
  when: java_version in packages[ansible_os_family]
