---
# ********************
# *** HIVE section ***
# ********************

- name: Find Hive dir
  shell: echo /opt/mapr/hive/hive-$(cat /opt/mapr/hive/hiveversion)
  register: hive_dir

- name: Copy hive-site.xml
  template: src=hive/hive-site.xml.{{security}} dest={{ hive_dir.stdout }}/conf/hive-site.xml

- name: Restart hs2
  shell: "maprcli node services -name hs2 -action restart -nodes {{ packages_eco.hiveserver2.host|first_host }}"
  become_user: mapr
  when: hostname in packages_eco.spark_thriftserver.host
