#*****************************
#*** Configure for Centos7 ***
#*****************************

- block:
  - name: Install Mesos dependencies - EPEL install
    yum: name=epel-release

  - name: Configure wandisco-svn.repo for Mesos
    blockinfile:
      dest: /etc/yum.repos.d/wandisco-svn.repo
      create: yes
      block: |
        [WANdiscoSVN]
        name=WANdisco SVN Repo 1.9
        enabled=1
        baseurl=http://opensource.wandisco.com/centos/7/svn-1.9/RPMS/\$basearch/
        gpgcheck=1
        gpgkey=http://opensource.wandisco.com/RPM-GPG-KEY-WANdisco

  - name: Update systemd
    yum: name=systemd state=latest

  - name: Development Tools install
    shell: yum groupinstall -y "Development Tools"

  - name: Install Mesos dependencies
    yum: name={{ item }}
    with_items:
      - python-devel
      - python-six
      - python-virtualenv
      - java-1.8.0-openjdk-devel
      - zlib-devel
      - libcurl-devel
      - openssl-devel
      - cyrus-sasl-devel
      - cyrus-sasl-md5
      - apr-devel
      - subversion-devel
      - apr-util-devel

  when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version == '7')

#******************************
#*** Configure for Ubuntu14 ***
#******************************

- block:
  - name: Update packages
    apt:
      update_cache: yes

  - name: Install Mesos dependencies
    apt: name={{ item }}
    with_items:
      - build-essential
      - python-dev
      - python-six
      - python-virtualenv
      - libcurl4-nss-dev
      - libsasl2-dev
      - libsasl2-modules
      - libapr1-dev
      - libsvn-dev

  when: (ansible_os_family == 'Debian') and (ansible_distribution_major_version == '14')

#******************************
#*** Configure for Ubuntu16 ***
#******************************

- block:
  - name: Update packages
    apt:
      update_cache: yes

  - name: Install Mesos dependencies
    apt: name={{ item }}
    with_items:
      - build-essential
      - python-dev
      - python-six
      - python-virtualenv
      - libcurl4-nss-dev
      - libsasl2-dev
      - libsasl2-modules
      - libapr1-dev
      - libsvn-dev
      - zlib1g-dev

  when: (ansible_os_family == 'Debian') and (ansible_distribution_major_version == '16')

#*********************
#*** Install Mesos ***
#*********************

- name: Create Mesos directory
  shell: mkdir /opt/mapr/mesos

- name: Make mapr owner of Mesos directory
  shell: chown mapr:mapr /opt/mapr/mesos

- name: Download Mesos
  get_url:
    url: http://repo.mapr/mesos-1.3.0-ubuntu1604.tar.gz
    dest: /opt/mapr/mesos/mesos-1.3.0.tar.gz
    owner: mapr
    mode: 0644
  when: (ansible_os_family == 'Debian') and (ansible_distribution_major_version == '16')

- name: Download Mesos
  get_url:
    url: http://repo.mapr/mesos-1.3.0-ubuntu1404.tar.gz
    dest: /opt/mapr/mesos/mesos-1.3.0.tar.gz
    owner: mapr
    mode: 0644
  when: (ansible_os_family == 'Debian') and (ansible_distribution_major_version == '14')

- name: Download Mesos
  get_url:
    url: http://repo.mapr/mesos-1.3.0-centos.tar.gz
    dest: /opt/mapr/mesos/mesos-1.3.0.tar.gz
    owner: mapr
    mode: 0644
  when: (ansible_os_family == 'RedHat')

- name: Unpack Mesos
  shell: tar -xvf /opt/mapr/mesos/mesos-1.3.0.tar.gz -C /opt/mapr/mesos

- name: Install Mesos
  shell: cd /opt/mapr/mesos/mesos-1.3.0/build; \
         make install
