- name: Install pexpect
  shell: pip install pexpect
  sudo: yes

- name: Generate truststorepassword
  become: yes
  become_user: mapr
  expect:
    command: hadoop credential create spark.ssl.truststorepassword -provider jceks://file/home/mapr/test.jceks
    responses:
      'Enter password:' : "mapr123"
      'Enter password again:' : "mapr123"

- name: Generate keystorepassword
  become: yes
  become_user: mapr
  expect:
    command: hadoop credential create spark.ssl.keystorepassword -provider jceks://file/home/mapr/test.jceks
    responses:
      'Enter password:' : "mapr123"
      'Enter password again:' : "mapr123"

- name: Generate keypassword
  become: yes
  become_user: mapr
  expect:
    command: hadoop credential create spark.ssl.keypassword -provider jceks://file/home/mapr/test.jceks
    responses:
      'Enter password:' : "mapr123"
      'Enter password again:' : "mapr123"


- name: Maprlogin password
  shell: "maprlogin password -user mapr <<< mapr"
  args:
    executable: /bin/bash
  become: yes
  become_user: mapr
  when: security == "maprsasl"

- name: Create mapr home directory
  become: yes
  become_user: mapr
  shell: hadoop fs -mkdir /user/mapr
  ignore_errors: yes

- name: Copy jceks to maprfs
  become: yes
  become_user: mapr
  shell: hadoop fs -put /home/mapr/test.jceks /user/mapr/spark-security-provider.jceks
  ignore_errors: yes
