---
# **********************************
# ***** SPARK ON MESOS CONFIG ******
# **********************************

- name: Edit spark-env.sh
  blockinfile:
    dest: "{{ spark_home_dir.stdout }}/conf/spark-env.sh"
    marker: "### Auto added ###"
    block: |
      export SPARK_EXECUTOR_URI=maprfs:///spark-{{spark_version.stdout|version_slice(3)}}.tgz
      export MESOS_NATIVE_JAVA_LIBRARY=/opt/mapr/mesos/mesos-1.3.0/build/src/.libs/libmesos.so
      MAPR_MESOS_CLASSPATH=$MAPR_SPARK_CLASSPATH

- name: Edit spark-defaults.conf
  blockinfile:
    dest: "{{ spark_home_dir.stdout }}/conf/spark-defaults.conf"
    marker: "### Auto added ###"
    block: |
      spark.executor.uri maprfs:///spark-{{spark_version.stdout|version_slice(3)}}.tgz

- name: Make Spark tar archive
  shell: |
    cd {{ spark_home_dir.stdout }}/..
    tar -czvf spark-{{spark_version.stdout|version_slice(3)}}.tgz spark-{{spark_version.stdout|version_slice(3)}}
    chown -R mapr:mapr spark-{{spark_version.stdout|version_slice(3)}}.tgz
    chmod 777 spark-{{spark_version.stdout|version_slice(3)}}.tgz
    hadoop fs -test -e /spark-{{spark_version.stdout|version_slice(3)}}.tgz || hadoop fs -put spark-{{spark_version.stdout|version_slice(3)}}.tgz /
  become: true
  become_user: mapr
