---
# **********************************
# **** SPARK1.6 HIVE1.2 CONFIG *****
# **********************************

  - name: Copy hive-site.xml to the Spark conf directory
    shell: ln -s /opt/mapr/hive/hive-1.2/conf/hive-site.xml /opt/mapr/spark/spark-1.6.1/conf
    become: true
    become_user: mapr

  - name: Change hive_versions property in compatibility.version
    replace:
      path: /opt/mapr/spark/spark-1.6.1/mapr-util/compatibility.version
      regexp: 'hive_versions='
      replace: 'hive_versions=1.2.1'

  - name: Find datanucleus-api
    shell: echo /opt/mapr/hive/hive-1.2/lib/datanucleus-api-jdo-*
    register: datanucleusapi

  - name: Find datanucleus-core
    shell: echo /opt/mapr/hive/hive-*/lib/datanucleus-core-*
    register: datanucleuscore

  - name: Find datanucleus-rdbms
    shell: echo /opt/mapr/hive/hive-*/lib/datanucleus-rdbms-*
    register: datanucleusrdbms

  - name: Add spark.sql.hive.metastore.version to the spark-defaults.conf
    lineinfile:
      dest=/opt/mapr/spark/spark-1.6.1/conf/spark-defaults.conf
      line="spark.sql.hive.metastore.version 1.2.1"

  - name: Add spark.yarn.dist.files to the spark-defaults.conf
    lineinfile:
      dest=/opt/mapr/spark/spark-1.6.1/conf/spark-defaults.conf
      line="spark.yarn.dist.files maprfs://{{ datanucleusapi.stdout }},maprfs://{{ datanucleuscore.stdout }},maprfs://{{ datanucleusrdbms.stdout }},maprfs:///opt/mapr/hive/hive-1.2/conf/hive-site.xml"

  - name: Create directories in maprfs
    shell: hadoop fs -mkdir -p /opt/mapr/hive/hive-1.2/lib; \
           hadoop fs -mkdir -p /opt/mapr/hive/hive-1.2/conf
    become: true
    become_user: mapr

  - name: Put files in maprfs
    shell: hadoop fs -put {{ datanucleusapi.stdout }} /opt/mapr/hive/hive-1.2/lib/; \
           hadoop fs -put {{ datanucleuscore.stdout }} /opt/mapr/hive/hive-1.2/lib/; \
           hadoop fs -put {{ datanucleusrdbms.stdout }} /opt/mapr/hive/hive-1.2/lib/; \
           hadoop fs -put /opt/mapr/hive/hive-1.2/conf/hive-site.xml /opt/mapr/hive/hive-1.2/conf/
    become: true
    become_user: mapr
