apiVersion: v1
kind: PersistentVolume
metadata:
  name: mapr-static-rw-pv
spec:
  storageClassName: mysc #Use stub SC explicitly if not set as default
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  csi:
    nodePublishSecretRef:
      name: "mapr-provisioner-secrets"
      namespace: "default"
    driver: com.mapr.csi-kdf
    volumeHandle: test-id
    volumeAttributes:
      volumePath: /static-model
      cluster: cyber.mapr.cluster
      cldbHosts: 192.168.33.11
      securityType: "unsecure" # Default: Unsecure