---

##################
### Non Secure ###
##################

  - name: Run configre.sh (simple)
    command: >
      /opt/mapr/server/configure.sh
      -C {{ packages_core.cldb.host|first_host|pick(fqdns) }}
      -Z {{ packages_core.zookeeper.host|first_host|pick(fqdns) }}
      -N {{ cluster_name }}
      -HS {{ packages_core.historyserver.host|first_host|pick(fqdns) }}
      -u mapr
      -g mapr
      -v
      -f
      -F /mapr-disks/disks.list
    when: (security == "none")


##################################
### Primary node with security ###
##################################

  - name: Run configure.sh (maprsasl | genkeys)
    command: >
      /opt/mapr/server/configure.sh
      -C {{ packages_core.cldb.host|first_host|pick(fqdns) }}
      -Z {{ packages_core.zookeeper.host|first_host|pick(fqdns) }}
      -N {{ cluster_name }}
      -HS {{ packages_core.historyserver.host|first_host|pick(fqdns) }}
      -u mapr
      -g mapr
      -v
      -f
      -F /mapr-disks/disks.list
      -secure
      -genkeys
    when: (security == "maprsasl") and (is_primary)

  - name: Run configre.sh (kerberos | genkeys)
    command: >
      /opt/mapr/server/configure.sh
      -C {{ packages_core.cldb.host|first_host|pick(fqdns) }}
      -Z {{ packages_core.zookeeper.host|first_host|pick(fqdns) }}
      -N {{ cluster_name }}
      -HS {{ packages_core.historyserver.host|first_host|pick(fqdns) }}
      -u mapr
      -g mapr
      -v
      -f
      -F /mapr-disks/disks.list
      -secure
      -genkeys
      -kerberosEnable
      -P {{ mapr_cluster_name_principal }}
    when: (security == "kerberos") and (is_primary)


  - name: Make a directory for public copy of security keys for VMLab
    command: mkdir -p /home/mapr/security_keys
    when: (security != "none") and (is_primary)

  - name: Make a public copy of security keys for VMLab
    command: cp /opt/mapr/conf/{{ item.file }} /home/mapr/security_keys
    when: (security in item.security) and (is_primary)
    with_items:
      - { file: maprserverticket, security: [ kerberos, maprsasl ] }
      - { file: ssl_keystore,     security: [ kerberos, maprsasl ] }
      - { file: ssl_truststore,   security: [ kerberos, maprsasl ] }
      - { file: mapr.keytab,      security: [ kerberos ]           }

  - name: Change permissions for public copy of security keys
    file: path=/home/mapr/security_keys/ state=directory recurse=yes owner=mapr group=mapr mode='u+rw,go+r'
    when: is_primary


#####################################
### Secondary nodes with security ###
#####################################

  - name: Get security keys
    command: scp -o StrictHostKeyChecking=no mapr@{{ primary_host }}:security_keys/{{ item.file }} /opt/mapr/conf/
    register: return_value
    until: return_value|success
    retries: 100
    delay: 10
    with_items:
      - { file: maprserverticket, security: [ kerberos, maprsasl ] }
      - { file: ssl_keystore,     security: [ kerberos, maprsasl ] }
      - { file: ssl_truststore,   security: [ kerberos, maprsasl ] }
      - { file: mapr.keytab,      security: [ kerberos ]           }
    when: (security in item.security) and (not is_primary)

  - name: Change owner and permissions for security keys
    file: path=/opt/mapr/conf/{{ item.file }} owner=mapr group=mapr mode={{ item.mode }}
    with_items:
      - { file: maprserverticket, mode: 600, security: [ kerberos, maprsasl ] }
      - { file: ssl_keystore,     mode: 400, security: [ kerberos, maprsasl ] }
      - { file: ssl_truststore,   mode: 444, security: [ kerberos, maprsasl ] }
      - { file: mapr.keytab,      mode: 600, security: [ kerberos ]           }
    when: (security in item.security) and (not is_primary)


  - name: Run configre.sh (maprsasl | no genkeys)
    command: /opt/mapr/server/configure.sh -C {{ packages_core.cldb.host|first_host|pick(fqdns) }} -Z {{ packages_core.zookeeper.host|first_host|pick(fqdns) }} -N {{ cluster_name }} -HS {{ packages_core.historyserver.host|first_host|pick(fqdns) }} -u mapr -g mapr  -v  -f -F /mapr-disks/disks.list -secure
    when: (security == "maprsasl") and (not is_primary)

  - name: Run configre.sh (kerberos | no genkeys)
    command: /opt/mapr/server/configure.sh -C {{ packages_core.cldb.host|first_host|pick(fqdns) }} -Z {{ packages_core.zookeeper.host|first_host|pick(fqdns) }} -N {{ cluster_name }} -HS {{ packages_core.historyserver.host|first_host|pick(fqdns) }} -u mapr -g mapr  -v  -f -F /mapr-disks/disks.list -secure -kerberosEnable
    when: (security == "kerberos") and (not is_primary)
