apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mapr-dynamic-sc
provisioner: com.mapr.csi-kdf
parameters:
  csiProvisionerSecretName: "mapr-provisioner-secrets"
  csiProvisionerSecretNamespace: "default"
#  only for secure clusters
#  csiNodePublishSecretName: "mapr-ticket-secret"
#  csiNodePublishSecretNamespace: "dynamic-csi"
  restServers: "192.168.33.11"
  cldbHosts: "192.168.33.11"
  cluster: "cyber.mapr.cluster"
  securityType: "unsecure"
  namePrefix: "csi-pv"
  mountPrefix: "/"
  advisoryquota: "1000M"
reclaimPolicy: Retain
