---
# ***************************
# *** YARN tests section ***
# ***************************

- name: Clone tests
  command: git clone -b master --depth 1 --single-branch https://6936784d69eb813cbcdf18ed2554e174f6f974ce@github.com/mapr/private-qa.git
  become: true
  become_user: mapr

- name: Set YARN Debug level
  shell: sed -i 's/INFO,RFA/DEBUG,RFA/g' /opt/mapr/hadoop/hadoop-2.*/sbin/yarn-daemon.sh

- name: Install mlocate
  package: name=mlocate state=present
  
- name: Update mlocate db
  command: updatedb

- name: Install screen
  package: name=screen state=present 
  