---

- name: Install MapR packages
  apt: name={{ item.value.package }} force=yes
  with_dict: "{{ packages_core }}"
  when: (ansible_os_family == 'Debian') and (hostname in item.value.host)
  
- name: Install MapR core patch
  apt: name=mapr-patch force=yes
  when: (ansible_os_family == 'Debian' and use_core_patch)

#----------------------------------------------------------

- name: Install MapR packages
  yum: name={{ item.value.package }}
  with_dict: "{{ packages_core }}"
  when: (ansible_os_family == 'RedHat') and (hostname in item.value.host)

- name: Install MapR packages
  yum: name=mapr-patch
  when: (ansible_os_family == 'RedHat' and use_core_patch)

#----------------------------------------------------------

- name: Install mapr-compat-suse
  zypper: name=mapr-compat-suse
  when: (ansible_os_family == 'Suse')

- name: Install MapR packages
  zypper: name={{ item.value.package }}
  with_dict: "{{ packages_core }}"
  when: (ansible_os_family == 'Suse' and hostname in item.value.host)

- name: Install MapR packages
  zypper: name=mapr-patch
  when: (ansible_os_family == 'Suse' and use_core_patch)
