apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: streaming
  name: streaming
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: streaming
    spec:
      containers:
      - image: diptan/streaming:latest
        name: streaming
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: model
      restartPolicy: Always
      volumes:
      - name: model
        persistentVolumeClaim:
          claimName: model
status: {}
