apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: diptan/web:latest
        name: web
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: model
      restartPolicy: Always
      volumes:
      - name: model
        persistentVolumeClaim:
          claimName: model
status: {}
