version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 
    depends_on:
      - zookeeper
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4'
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  elasticsearch-mapping-init:
    build: ./elasticsearch-mapping-init
    image: diptan/elasticsearch-mapping-init
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  rsscollector:
    build: ./logstash/docker
    image: diptan/rsscollector
  mongo:
    build: ./mongo
    image: diptan/mongo
    ports:
      - '27017:27017'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: ivan123
    ports:
      - 5432:5432
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 18080:8080
  web:
    build: ../web
    image: diptan/web:latest
    ports: 
      - 8080:8080
    depends_on:
      - db
    # volumes:
    #   - model:/tmp
  streaming:
    build: ../streamer
    image: diptan/streamer:latest
    depends_on:
      - kafka
      - mongo
    # volumes:
    #   - model:/tmp
  trainer:
    build: ../trainer
    image: diptan/trainer:latest
    ports:
      - 8088:8088

volumes:
  esdata:
    driver: local
  model:
    driver: local
