version: '3'

services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  mongo:
    build: ./mongo
    image: diptan/mongo
    ports:
      - 27017:27017
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: ivan123
    ports:
      - 5432:5432
  web:
    build: ../web
    image: diptan/web:latest
    ports: 
      - 8080:8080
    depends_on:
      - db
    volumes:
      - model:/tmp
  crawler:
    build: ../crawler
    image: diptan/crawler:latest
    ports:
      - 8083:8083
    depends_on:
      - kafka
volumes:
  esdata:
    driver: local
  model:
    driver: local
