version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
     - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ENABLE_KRAFT=no
    depends_on:
      - zookeeper
  mongo:
    build: ./mongo
    image: diptan/mongo
    ports:
      - '27017:27017'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: ivan123
    ports:
      - 5432:5432
  web:
    build: ../web
    image: diptan/web:latest
    ports: 
      - 8080:8080
    depends_on:
      - db
    volumes:
      - model:/tmp
  streamer:
    build: ../streamer
    image: diptan/streamer:latest
    ports:
      - 8082:8082
      - 4040:4040
    depends_on:
      - kafka
      - mongo
    volumes:
      - model:/model
  trainer:
    build: ../trainer
    image: diptan/trainer:latest
    ports:
      - 8081:8081
    volumes:
      - model:/model

  crawler:
    build: ../crawler
    image: diptan/crawler:latest
    ports:
      - 8083:8083

volumes:
  esdata:
    driver: local
  model:
    driver: local
