version: '3'

services:
  kafka:
    image: bitnami/kafka:3.6
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  schema-registry:
    image: bitnami/schema-registry:7.5
    ports:
      - 8081:8081
    environment:
      - SCHEMA_REGISTRY_DEBUG=true
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    depends_on:
      - kafka
  mongo:
    build: ./mongo
    ports:
      - 27017:27017
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: ivan123
    ports:
      - 5432:5432
  web:
    build: ../web
    ports:
      - 8080:8080
    depends_on:
      - db
  crawler:
    build: ../crawler
    ports:
      - 8083:8083
    depends_on:
      - kafka
  processor:
    build: ../processor

volumes:
  esdata:
    driver: local
  model:
    driver: local
