apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    io.kompose.service: kafka
spec:
  containers:
  - env:
    # - name: KAFKA_BROKER_ID
    #   value: "1"
    # - name: KAFKA_LOG4J_ROOT_LOGLEVEL
    #   value: DEBUG
    - name: ALLOW_PLAINTEXT_LISTENER
      value: "yes"
    - name: KAFKA_CFG_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_CFG_LISTENERS
      value: PLAINTEXT://kafka:9092
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: PLAINTEXT://kafka:9092
    image: bitnami/kafka:latest
    name: kafka
    ports:
    - containerPort: 9092
  restartPolicy: Always
