apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
      - env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        image: bitnami/zookeeper:latest
        name: zookeeper
        ports:
        - containerPort: 2181
      restartPolicy: Always
