---
- hosts: "{{ hostname }}"
  remote_user: mapr
  sudo: yes

  vars:
    java_version: openjdk8 # available values: openjdk7 / openjdk8 / openjdk11
    databases:
      mysql:    { host: [ node1 ] }
      mariadb:  { host: [ ] }
      postgres: { host: [ ] }
      mongo:    { host: [ ] }

  roles:
    - setup-initial
    - setup-database
    #- setup-ldap
