---
- name: Stop mapr-warden
  service: name=mapr-warden state=stopped

- name: Stop mapr-zookeeper
  service: name=mapr-zookeeper state=stopped
  ignore_errors: true

- name: Install Ecosystem software
  package: name={{ item.package }}
  when: (hostname in item.host)
  with_items:
      - "{{ packages_eco.hbase }}"
      - "{{ packages_eco.hbase_master }}"
      - "{{ packages_eco.hbase_regionserver }}"
      - "{{ packages_eco.hbase_rest }}"
      - "{{ packages_eco.hbasethrift }}"
      - "{{ packages_eco.spark }}"
      - "{{ packages_eco.spark_historyserver }}"
      - "{{ packages_eco.spark_master }}"
      - "{{ packages_eco.spark_thriftserver }}"
      - "{{ packages_eco.hue_livy }}"
      - "{{ packages_eco.kafka }}"
      - "{{ packages_eco.tez }}"
      - "{{ packages_eco.hive }}"
      - "{{ packages_eco.hiveserver2 }}"
      - "{{ packages_eco.hivemetastore }}"
      - "{{ packages_eco.hivewebhcat }}"
      - "{{ packages_eco.impala }}"
      - "{{ packages_eco.impala_server }}"
      - "{{ packages_eco.impala_statestore }}"
      - "{{ packages_eco.impala_catalog }}"
      - "{{ packages_eco.hue }}"
      - "{{ packages_eco.httpfs }}"
      - "{{ packages_eco.oozie }}"
      - "{{ packages_eco.oozie_internal }}"
      - "{{ packages_eco.pig }}"
      - "{{ packages_eco.sqoop2_client }}"
      - "{{ packages_eco.sqoop2_server }}"
      - "{{ packages_eco.sqoop }}"
      - "{{ packages_eco.sentry }}"
      - "{{ packages_eco.flume }}"
      - "{{ packages_eco.drill }}"
      - "{{ packages_eco.mahout }}"
      - "{{ packages_eco.schema_registry }}"

