- name: Include MySQL setup scenario
  include: setup_mysql.yml
  when: hostname in databases.mysql.host

- name: Include MariaDB setup scenario
  include: setup_mariadb.yml
  when: hostname in databases.mariadb.host

- name: Include PostgreSQL setup scenario
  include: setup_postgres.yml
  when: hostname in databases.postgres.host

- name: Include Mongo setup scenario
  include: setup_mongo.yml
  when: hostname in databases.mongo.host
