---

# Note: By default MySQL-python uses file socket connection when host=localhost.
# So we connect with host=127.0.0.1 to force host/port connection,
# as by default MariaDB has no file socket on Suse.

  - name: Add MariaDB package key [RedHat/Suse]
    command: rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    when: ansible_os_family in ['RedHat', 'Suse']

  - name: Add MariaDB repository [RedHat]
    template: src=mariadb.repo.j2 dest=/etc/yum.repos.d/mariadb.repo
    when: ansible_os_family in ['RedHat']

  - name: Add MariaDB repository [Suse]
    template: src=mariadb.repo.j2 dest=/etc/zypp/repos.d/mariadb.repo
    when: ansible_os_family in ['Suse']

  - name: Add MariaDB package key [Debian]
    block:
      - apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db state=present
        when: ansible_distribution_major_version == '14'
      - apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8 state=present
        when: ansible_distribution_major_version == '16'
      - apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8 state=present
        when: ansible_distribution_major_version == '18'
    when: ansible_os_family in ['Debian']

  - name: Add MariaDB repository [Debian]
    apt_repository: repo='{{ mariadb_repo[ansible_os_family][ansible_distribution_major_version] }}' state=present update_cache=yes
    when: ansible_os_family in ['Debian']

  - name: Install MariaDB [Debian]
    package: name=mariadb-server
    when: ansible_os_family in ['Debian']

  - name: Install Mysql-Python [Debian]
    package: name=python-mysqldb
    when: ansible_os_family in ['Debian']

  - name: Install MariaDB [RedHat]
    package: name=MariaDB-server
    when: ansible_os_family in ['RedHat']

  - name: Install MariaDB [Suse]
    package: name=MariaDB-server
    when: ansible_os_family in ['Suse']

  - find: patterns="my.cnf" paths="/etc,/etc/mysql,/usr/etc"
    register: my_cnf_path

  - name: Comment bind-address property
    lineinfile: dest={{ item.path }} regexp="^bind-address.*" line="#bind-address="
    with_items: "{{ my_cnf_path.files }}"

  - name: Restart the MariaDB service
    service: name=mysql state=restarted enabled=yes

  - name: Create MariaDB superuser
    mysql_user: login_user=root login_password="" login_host="127.0.0.1" name=root password="{{ database_root_password }}" host="%" priv="*.*:ALL,GRANT"

  - name: Remove MariaDB default users
    mysql_user: login_user=root login_password="" login_host="127.0.0.1" name="" host="{{ item }}" state=absent
    with_items: [ "127.0.0.1", "{{ fqdn }}", "::1", "localhost" ]

  - name: Remove MariaDB default superusers
    mysql_user: login_user=root login_password="" login_host="127.0.0.1" name=root host="{{ item }}" state=absent
    with_items: [ "127.0.0.1", "{{ fqdn }}", "::1", "localhost" ]
