---

# Note: we can not use host=127.0.0.1 hack here, as we did for MariaDB.
# Everything is fine with file socket for MySQL on Suse,
# and host=127.0.0.1 will not work, as MySQL on Ubuntu 16.04 has no root@127.0.0.1 user.

  - name: Add MySQL Community repository [RedHat]
    template: src=mysql.repo.j2 dest=/etc/yum.repos.d/mysql.repo
    when: ansible_os_family in ['RedHat']

  - name: Add MySQL Community repository [Suse]
    template: src=mysql.repo.j2 dest=/etc/zypp/repos.d/mysql.repo
    when: ansible_os_family in ['Suse']

  - name: Install MYSQL [Debian]
    package: name=mysql-server
    when: ansible_os_family in ['Debian']

  - name: Install Mysql-Python [Debian]
    package: name=python-mysqldb
    when: ansible_os_family in ['Debian']

  - name: Install MYSQL [RedHat]
    package: name=mysql-server
    when: ansible_os_family in ['RedHat']

  - name: Install MYSQL [Suse]
    package: name=mysql-community-server
    when: ansible_os_family in ['Suse']

  - find: patterns="my.cnf,mysqld.cnf" paths="/etc,/etc/mysql,/usr/etc,/etc/mysql/mysql.conf.d"
    register: my_cnf_path

  - name: Comment bind-address property
    lineinfile: dest={{ item.path }} regexp="^bind-address.*" line="#bind-address="
    with_items: "{{ my_cnf_path.files }}"

  - name: Restart the mysql service [Debian/Suse]
    service: name=mysql state=restarted enabled=yes
    when: ansible_os_family in ['Debian', 'Suse']

  - name: Restart the mysql service [RedHat]
    service: name=mysqld state=restarted enabled=yes
    when: ansible_os_family in ['RedHat']

  - name: Create MySQL superuser
    mysql_user: login_user=root login_password="" name=root password="{{ database_root_password }}" host="%" priv="*.*:ALL,GRANT"

  - name: Remove MySQL default users
    mysql_user: login_user=root login_password="" name="" host="{{ item }}" state=absent
    with_items: [ "127.0.0.1", "{{ fqdn }}", "::1", "localhost" ]

  - name: Remove MySQL default superusers
    mysql_user: login_user=root login_password="" name=root host="{{ item }}" state=absent
    with_items: [ "127.0.0.1", "{{ fqdn }}", "::1", "localhost" ]
