---

  # TODO: Add SuSE

  - name: Add Mongo Community repository [RedHat]
    template: src=mongodb.repo.j2 dest=/etc/yum.repos.d/mongodb.repo
    when: ansible_os_family in ['RedHat']

  - name: Install Mongo [Debian]
    apt: name=mongodb
    when: ansible_os_family in ['Debian']

  - name: Install Mongo [RedHat]
    yum: name=mongodb-org
    when: ansible_os_family in ['RedHat']

  - name: Start the mongo service [Debian]
    service: name=mongodb state=started enabled=yes
    when: ansible_os_family in ['Debian']

  - name: Start the mongo service [RedHat]
    service: name=mongod state=started enabled=yes
    when: ansible_os_family in ['RedHat']
