 - name: Add ldapuser into system
   user: name={{ ldap_user }} uid=5100

 - name: Install LDAP client packages [Ubuntu]
   apt: name=ldap-utils
   when: ansible_os_family == 'Debian'

 - name: Install LDAP client packages [RedHat]
   yum: name=openldap-clients
   when: ansible_os_family == 'RedHat'

 - name: Install LDAP client packages [Suse]
   zypper: name=openldap2-client
   when: ansible_os_family == 'Suse'

 - name: Find LDAP client configuration file
   find: paths="/etc/ldap/,/etc/openldap/" patterns="ldap.conf"
   register: ldap_confs

 - name: Configure LDAP client / set BASE
   lineinfile: dest={{ ldap_confs.files[0].path }} regexp="^BASE" line="BASE {{ ldap_base }}"

 - name: Configure LDAP client / set URI
   lineinfile: dest={{ ldap_confs.files[0].path }} regexp="^URI" line="URI ldap://{{ ldap_server_host }}"
