# Insall LDAP server packages

 - name: Insall LDAP server packages [Suse]
   zypper: name=openldap2
   when: ansible_os_family == 'Suse'

 - name: Insall LDAP server packages [Ubuntu]
   apt: name=slapd
   when: ansible_os_family == 'Debian'

 - name: Insall LDAP server packages [RedHat]
   yum: name=openldap-servers
   when: ansible_os_family == 'RedHat'

 - name: Start LDAP server
   service: name=slapd state=restarted enabled=yes

 - name: Wait for LDAP server port
   wait_for: host={{ hostname }} port=389

 - name: Find LDAP conf dir
   find: paths="/etc" patterns="ldap,openldap" file_type=directory
   register: ldap_conf_dir
 - set_fact: ldap_conf_dir={{ ldap_conf_dir.files[0].path }}

# Configure LDAP server on Suse [ slapd.conf method ]

 - name: Configure LDAP server [ slapd.conf method ]
   when: ansible_os_family == 'Suse'
   block:
    - name: Configure LDAP server [ slapd.conf ] / change suffix
      lineinfile: dest="{{ ldap_conf_dir }}/slapd.conf" regexp="^suffix" line="suffix \"{{ ldap_base }}\""

    - name: Configure LDAP server [ slapd.conf ] / change rootdn
      lineinfile: dest="{{ ldap_conf_dir }}/slapd.conf" regexp="^rootdn" line="rootdn \"cn={{ ldap_admin }},{{ ldap_base }}\""

    - name: Configure LDAP server [ slapd.conf ] / change rootpw
      lineinfile: dest="{{ ldap_conf_dir }}/slapd.conf" regexp="^rootpw" line="rootpw {{ ldap_admin_password }}"


# Configure LDAP server on RedHat and Ubuntu [ slapd-config method ]

 - name: Configure LDAP server [ slapd-config method ] / get base DN for configs
   when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
   block:
    - name: Configure LDAP server [ slapd-config method ] / get base DN for configs
      command: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn=config olcSuffix=* 1.1
      register: base_dn

    - name: Configure LDAP server [ slapd-config method ] / get olcAccess DN for configs
      command: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn=config olcAccess=* 1.1
      register: access_dn

    - name: Configure LDAP server [ slapd-config method ] / Create ldif to set olcSuffix, olcRootDN, olcRootPW and olcAccess
      template: src=slapd-config.ldif.j2 dest=/tmp/slapd-config.ldif

    - name: Configure LDAP server [ slapd-config method ] / ldapmodify slapd-config.ldif
      command: ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/slapd-config.ldif

    - name: Load LDAP schemas that used in our ldap-init.ldif [ slapd-config method ]
      command: ldapadd -Y EXTERNAL -H ldapi:/// -f {{ item }}
      ignore_errors: true
      with_items:
       - "{{ ldap_conf_dir }}/schema/cosine.ldif"
       - "{{ ldap_conf_dir }}/schema/inetorgperson.ldif"


# Restart LDAP server with new configuration

 - name: Restart LDAP server
   service: name=slapd state=restarted enabled=yes

 - name: Wait for LDAP server port
   wait_for: host={{ hostname }} port=389


# Load inital ldif

 - name: Create ldap-init.ldif
   template: src=ldap-init.ldif.j2 dest=/tmp/ldap-init.ldif

 - name: ldapadd ldap-init.ldiff
   shell: "ldapadd -x -D cn={{ ldap_admin }},{{ ldap_base }} -w {{ ldap_admin_password }} -f /tmp/ldap-init.ldif"
