---

 - name: Add /usr/lib/mit/*bin/ to be available from sudo
   template: src=sudoers_suse_kerberos.j2 dest=/etc/sudoers.d/sudoers_suse_kerberos
   when: (ansible_os_family == "Suse")


 - include: setup-server.yml
   when:  '"{{ kerberos_server_host }}" == "{{ hostname }}"'

 - include: setup-client.yml
   when:  '"{{ kerberos_server_host }}" != "{{ hostname }}"'


 - name: Copy maprlogin_kerberos.sh to /home/mapr
   template: src=maprlogin_kerberos.sh.j2 dest=/home/mapr/maprlogin_kerberos.sh mode=777
