---

- name: Restart kadmin and krb5kdc
  service: name="{{item}}" state=restarted enabled=yes
  with_items:
    - krb5-kdc
    - krb5-admin-server
  when: (ansible_os_family == 'Debian')

- name: Restart kadmin and krb5kdc
  service: name="{{item}}" state=restarted enabled=yes
  with_items:
    - krb5kdc
    - kadmin
  when: (ansible_os_family == 'RedHat')

- name: Restart kadmin and krb5kdc
  service: name="{{item}}" state=restarted enabled=yes
  with_items:
    - krb5kdc
    - kadmind
  when: (ansible_os_family == 'Suse')
