---

  - name: Install kerberos packages [Ubuntu]
    apt: name={{ item }} force=yes
    with_items: "{{ server_ubuntu_kerberos_packages }}"
    when: (ansible_os_family == 'Debian')

  - name: Install kerberos packages [Centos]
    yum: name={{ item }}
    with_items: "{{ server_centos_kerberos_packages }}"
    when: (ansible_os_family == 'RedHat')

  - name: Install kerberos packages [Suse]
    zypper: name={{ item }}
    with_items: "{{ server_suse_kerberos_packages }}"
    when: (ansible_os_family == 'Suse')

  #----------------------------------------------------------

  - name: Copy /etc/krb5.conf [Ubuntu]
    template: src=krb5.conf_ubuntu.j2 dest=/etc/krb5.conf
    when:  (ansible_os_family == 'Debian')

  - name: Copy /etc/krb5kdc/kadm5.acl [Ubuntu]
    template: src=kadm5.acl.j2 dest=/etc/krb5kdc/kadm5.acl
    when:  (ansible_os_family == 'Debian')

  - name: Copy /etc/krb5.conf [Centos]
    template: src=krb5.conf_centos.j2 dest=/etc/krb5.conf
    when: (ansible_os_family == 'RedHat')

  - name: Copy /var/kerberos/krb5kdc/kadm5.acl [Centos]
    template: src=kadm5.acl.j2 dest=/var/kerberos/krb5kdc/kadm5.acl
    when: (ansible_os_family == 'RedHat')

  - name: Copy /etc/krb5.conf [Suse]
    template: src=krb5.conf_suse.j2 dest=/etc/krb5.conf
    when: (ansible_os_family == 'Suse')

  - name: Copy /var/lib/kerberos/krb5kdc/kadm5.acl [Suse]
    template: src=kadm5.acl.j2 dest=/var/lib/kerberos/krb5kdc/kadm5.acl
    when: (ansible_os_family == 'Suse')

  #----------------------------------------------------------

  - name: Create KDC database
    command: kdb5_util create -s -r {{ realm }} -P {{ kerberos_password }}

  - name: Create principals for admin user
    shell: echo "addprinc -pw {{ kerberos_password }} root/admin@{{ realm }}" | kadmin.local

  - include: restart_kerberos.yml

  - name: Create principal for mapr/cluster_name
    shell: echo "addprinc -randkey {{ mapr_cluster_name_principal_short }}" | kadmin.local

  - name: Create principal for mapr/fqdn_name
    shell: echo "addprinc -randkey {{ item|pick(fqdns)|mkprinc(mapr_host_principal_short) }}" | kadmin.local
    with_items: "{{ enabled_hosts }}"

  - name: Create principal for HTTP/fqdn_name
    shell: echo "addprinc -randkey {{ item|pick(fqdns)|mkprinc(http_host_principal_short) }}" | kadmin.local
    with_items: "{{ enabled_hosts }}"

  - name: Create principal for impala/fqdn_name
    shell: echo "addprinc -randkey {{ item|pick(fqdns)|mkprinc(impala_host_principal_short) }}" | kadmin.local
    with_items: "{{ enabled_hosts }}"

  - name: Add principal mapr/cluster_name to mapr.keytab
    shell: echo "ktadd -k /opt/mapr/conf/mapr.keytab {{ mapr_cluster_name_principal }}" | kadmin.local

  - name: Add principal mapr/fqdn to mapr.keytab
    shell: echo "ktadd -k /opt/mapr/conf/mapr.keytab {{ item|pick(fqdns)|mkprinc(mapr_host_principal) }}" | kadmin.local
    with_items: "{{ enabled_hosts }}"

  - name: Add principal HTTP/fqdn to mapr.keytab
    shell: echo "ktadd -k /opt/mapr/conf/mapr.keytab {{ item|pick(fqdns)|mkprinc(http_host_principal) }}" | kadmin.local
    with_items: "{{ enabled_hosts }}"

  - name: Add principal impala/fqdn to mapr.keytab
    shell: echo "ktadd -k /opt/mapr/conf/mapr.keytab {{ item|pick(fqdns)|mkprinc(impala_host_principal) }}" | kadmin.local
    with_items: "{{ enabled_hosts }}"

  - name: Change owner and permissions for mapr.keytab
    file: path=/opt/mapr/conf/mapr.keytab owner=mapr group=mapr mode=600

  - name: Create principal for mapruser1/fqdn_name
    shell: echo "addprinc -randkey {{ item|pick(fqdns)|mkprinc(mapruser1_host_principal) }}" | kadmin.local
    with_items: "{{ enabled_hosts }}"

  - name: Add principal mapruser1/fqdn to mapruser1.keytab
    shell: echo "ktadd -k /home/mapruser1/mapruser1.keytab {{ item|pick(fqdns)|mkprinc(mapruser1_host_principal) }}" | kadmin.local
    with_items: "{{ enabled_hosts }}"

  - name: Change owner and permissions for mapruser1.keytab
    file: path=/home/mapruser1/mapruser1.keytab owner=mapruser1 group=mapruser1 mode=600

  - include: restart_kerberos.yml
