---

  - name: Install kerberos packages [Ubuntu]
    apt: name={{ item }} force=yes
    with_items:
      - "{{client_ubuntu_kerberos_packages}}"
    when: (ansible_os_family == 'Debian')

  - name: Install kerberos packages [Centos]
    yum: name={{ item }}
    with_items:
      - "{{ client_centos_kerberos_packages }}"
    when: (ansible_os_family == 'RedHat')

  - name: Install kerberos packages [Suse]
    zypper: name={{ item }}
    with_items:
      - "{{ client_suse_kerberos_packages }}"
    when: (ansible_os_family == 'Suse')

  #----------------------------------------------------------

  - name: Copy /etc/krb5.conf [Ubuntu]
    template: src=krb5.conf_ubuntu.j2 dest=/etc/krb5.conf
    when:  (ansible_os_family == 'Debian')

  - name: Copy /etc/krb5.conf [Centos]
    template: src=krb5.conf_centos.j2 dest=/etc/krb5.conf
    when: (ansible_os_family == 'RedHat')

  - name: Copy /etc/krb5.conf [Suse]
    template: src=krb5.conf_suse.j2 dest=/etc/krb5.conf
    when: (ansible_os_family == 'Suse')
