---

  - name: Maprlogin kerberos
    shell: "/home/mapr/maprlogin_kerberos.sh"
    become: yes
    become_user: mapr
    when: security == "kerberos"

  - name: Maprlogin password
    shell: "maprlogin password -user mapr <<< mapr"
    args:
        executable: /bin/bash
    become: yes
    become_user: mapr
    when: security == "maprsasl"

  - name: Add .bash_aliases import
    blockinfile:
      dest: /home/mapr/.bashrc
      block: |
        # Alias definitions.
        # You may want to put all your additions into a separate file like
        # ~/.bash_aliases, instead of adding them here directly.
        # See /usr/share/doc/bash-doc/examples in the bash-doc package.

        if [ -f ~/.bash_aliases ]; then
          . ~/.bash_aliases
        fi
      marker: "#  ANSIBLE MANAGED BLOCK "
      insertafter: EOF

  - template:
      src: templates/bash_aliases
      dest: /home/mapr/.bash_aliases
      owner: mapr
      group: mapr
      mode: "u=rw,g=r,o=r"
