---
# *********************
# *** HBASE section ***
# *********************

- name: Find HBase config dir
  shell: ls -d /opt/mapr/hbase/hbase-*/conf
  register: hbase_conf_dir

- name: Copy hbase-site.xml --| Kerberos |--
  template: src=hbase/hbase-site.xml.kerberos dest={{ hbase_conf_dir.stdout }}/hbase-site.xml
  when: (security == "kerberos")

- name: Change heapsize percent for warden
  lineinfile: dest=/opt/mapr/conf/warden.conf regexp=service.command.mfs.heapsize.percent line=service.command.mfs.heapsize.percent=5

- name: Change heapsize percent for hbase region server
  lineinfile: dest=/opt/mapr/conf/warden.conf regexp=service.command.hbregion.heapsize.percent line=service.command.hbregion.heapsize.percent=10
  ignore_errors: true

- name: Change min heapsize allocation for hbase region server
  lineinfile: dest=/opt/mapr/conf/warden.conf regexp=service.command.hbregion.heapsize.min line=service.command.hbregion.heapsize.min=512
  ignore_errors: true
