---
# *********************
# *** KAFKA section ***
# *********************

- name: Find Kafka home dir
  shell: ls -d /opt/mapr/kafka/kafka-*
  register: kafka_home_dir

- name: zookeeper.properties -> change port to 5181
  lineinfile: dest={{ kafka_home_dir.stdout }}/config/zookeeper.properties regexp=clientPort= line="clientPort=5181"
  ignore_errors: true

- name: server.properties -> change port to 5181
  lineinfile: dest={{ kafka_home_dir.stdout }}/config/server.properties regexp=zookeeper.connect= line="zookeeper.connect={{ packages_core.zookeeper.host|first_host }}:5181"
  ignore_errors: true

- name: Change Kafka Zookeeper properties
  lineinfile:
    dest={{ kafka_home_dir.stdout }}/config/server.properties
    line="delete.topic.enable=true"
    insertafter=EOF
  ignore_errors: true
