---

  - name: Get Spark version
    command: "{{ package_version }} mapr-spark"
    register: spark_version

  - name: Find Spark home dir
    shell: "ls -d /opt/mapr/spark/spark-* | tail -n1"
    register: spark_home_dir

  - name: Download javax.servlet-api-3.1.0.jar
    get_url:
        url: https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
        dest: "{{ spark_home_dir.stdout }}/lib"
        mode: 0666
    ignore_errors: true

  - name: Add javax.servlet-api.jar to SPARK_SUBMIT_CLASSPATH
    lineinfile:
        dest: "{{ spark_home_dir.stdout }}/conf/spark-env.sh"
        regexp: "SPARK_SUBMIT_CLASSPATH="
        line: "SPARK_SUBMIT_CLASSPATH=$SPARK_SUBMIT_CLASSPATH:{{ spark_home_dir.stdout }}/lib/javax.servlet-api-3.1.0.jar:$MAPR_SPARK_CLASSPATH"
    ignore_errors: true

  - name: "Install R [RedHat]"
    package: name=R-core
    when: ansible_os_family == 'RedHat'

  - name: "Install R [Debian]"
    package:
        name: [ r-base, r-base-dev ]
    when: ansible_os_family == 'Debian'

  # - name: Make ZIP of all Spark JARs and use it
  #   block:
  #     - archive:
  #           path: "{{ spark_home_dir.stdout }}/jars/"
  #           dest: "{{ spark_home_dir.stdout }}/spark-jars.zip"
  #           format: zip
  #     - lineinfile:
  #           dest: '{{ spark_home_dir.stdout }}/conf/spark-defaults.conf'
  #           line: 'spark.yarn.archive maprfs:////apps/spark/spark-jars.zip'
  #           insertafter: EOF
  #       ignore_errors: true
  #   when: spark_verstion.stdout|version_slice(3) == '2.0.1'
