---
# *********************
# *** Drill section ***
# *********************

- name: Find Drill home dir
  shell: ls -d /opt/mapr/drill/drill-*
  register: drill_home_dir

- name: Replace redundant heapsize.min requirement in warden-file template for drill-bits (MD-3046)
  lineinfile: path="{{ drill_home_dir.stdout }}/conf/warden.drill-bits.conf" regexp="service.heapsize.min=.*" line="service.heapsize.min=1024"
  ignore_errors: yes
