---
# *******************
# *** HUE section ***
# *******************

- name: Find Hue dir
  shell: ls -vd /opt/mapr/hue/hue-*
  register: hue_dir

- name: Copy hue-plugins-*.jar
  shell: cp {{ hue_dir.stdout_lines | last }}/desktop/libs/hadoop/java-lib/hue-plugins-*.jar /opt/mapr/hadoop/hadoop-0*/lib/
  when: packages_core.jobtracker.host


- name: Configure hue.ini
  template: src=hue/hue00vmlab.ini.j2 dest={{ hue_dir.stdout_lines | last }}/desktop/conf/hue00vmlab.ini


- name: Create Hue database
  mysql_db: name=hue login_user=root login_password={{ database_root_password }} login_host={{ (databases.mysql.host, databases.mariadb.host)|first_host }}
  when: (databases.mysql.host or databases.mariadb.host)
  ignore_errors: true

- name: Setup Hue databse
  shell: "source ./build/env/bin/activate; hue syncdb --noinput; hue migrate; deactivate"
  args:
    executable: /bin/bash
    chdir: "{{ hue_dir.stdout_lines | last }}"
  when: (databases.mysql.host or databases.mariadb.host)
  ignore_errors: true
