---
# *********************
# *** OOZIE section ***
# *********************

- name: Find Oozie config dir
  shell: ls -d /opt/mapr/oozie/oozie-*/conf
  register: oozie_conf_dir
  ignore_errors: true

- name: Copy oozie-site.xml
  template: src=oozie/oozie-site.xml.{{security}}
            dest={{ oozie_conf_dir.stdout }}/oozie-site.xml
            owner=root
            group=root
            mode=644
            backup=yes
  sudo: yes