--- 
# ***********************
# *** CLASSIC section ***
# ***********************

- name: Find CLASSIC config dir
  shell: ls -d /opt/mapr/hadoop/hadoop-0*/conf
  register: classic_conf_dir

- name: Copy core-site.xml
  template: src=classic/core-site.xml.{{security}}
            dest={{ classic_conf_dir.stdout }}/core-site.xml
            owner=root
            group=root
            mode=644
            backup=yes
  sudo: yes
  when: mapr_version <= 311

- name: Copy mapred-site.xml
  template: src=classic/mapred-site.xml.{{security}}
            dest={{ classic_conf_dir.stdout }}/mapred-site.xml
            owner=root
            group=root
            mode=644
            backup=yes
  sudo: yes
