---
# **********************
# *** Sentry section ***
# **********************


- name: Find Sentry dir
  shell: ls -vd /opt/mapr/sentry/sentry-*
  register: sentry_dir

- name: Copy sentry-site.xml
  template: src=sentry/sentry-site.xml.{{security}} dest={{ sentry_dir.stdout }}/conf/sentry-site.xml


- name: Create Sentry database
  mysql_db: name=sentry_store login_user=root login_password={{ database_root_password }} login_host={{ (databases.mysql.host, databases.mariadb.host)|first_host }}
  when: (databases.mysql.host or databases.mariadb.host)
  ignore_errors: true

- name: Setup Sentry DB Storage
  command: "{{ sentry_dir.stdout }}/bin/sentry --command schema-tool --conffile {{ sentry_dir.stdout }}/conf/sentry-site.xml --dbType mysql --initSchema"
  when: (databases.mysql.host or databases.mariadb.host) and (hostname == packages_eco.sentry.host|first_host)
  ignore_errors: true

- name: Copy warden.sentry.conf
  command: "cp {{ sentry_dir.stdout }}/conf.d/warden.sentry.conf /opt/mapr/conf/conf.d/"
  when: (hostname == packages_eco.sentry.host|first_host)