---
# **********************
# *** Impala section ***
# **********************

- name: Get Impala version
  command: "{{ package_version }} mapr-impala"
  register: impala_version
  ignore_errors: true

- name: Find Impala config dir
  shell: ls -d /opt/mapr/impala/impala-*/conf
  register: impala_conf_dir

- name: Copy Impala env.sh
  template: src=impala/env.sh.{{security}} dest={{ impala_conf_dir.stdout }}/env.sh

- name: Copy hive-site.xml
  template: src=hive/hive-site.xml.{{security}} dest={{ impala_conf_dir.stdout }}/hive-site.xml

- name: Copy core-site.xml
  template: src=yarn/core-site.xml.{{security}} dest={{ impala_conf_dir.stdout }}/core-site.xml
  when: (security == "kerberos")
