--- 
# **********************
# *** HTTPFS section ***
# **********************

- name: Find HttpFs config dir
  shell: ls -d /opt/mapr/httpfs/httpfs-*/etc/hadoop
  register: httpfs_conf_dir

- name: Copy httpfs-site.xml --| Kerberos |--
  template: src=httpfs/httpfs-site.xml.kerberos 
            dest={{ httpfs_conf_dir.stdout }}/httpfs-site.xml 
            owner=root 
            group=root 
            mode=644
            backup=yes
  sudo: yes
  when: (security == "kerberos")

- name: Copy core-site.xml to httpfs conf dir --| Kerberos |--
  template: src=yarn/core-site.xml.kerberos 
            dest={{ httpfs_conf_dir.stdout }}/core-site.xml 
            owner=root 
            group=root 
            mode=644
            backup=yes
  sudo: yes
  when: (security == "kerberos")