---

    ######################
    ### Hadoop section ###
    ######################
  - name: "env.sh -> replace MAPR_LOGIN_OPTS (for core < 5.1)"
    lineinfile: dest=/opt/mapr/conf/env.sh regexp=^MAPR_LOGIN_OPTS= line="MAPR_LOGIN_OPTS=\"-Dhadoop.login=hybrid ${MAPR_JAAS_CONFIG_OPTS} ${MAPR_ZOOKEEPER_OPTS}\""
    sudo: yes
    when: ((security == "kerberos") and (mapr_version < 510))

  - name: "env.sh -> replace MAPR_LOGIN_OPTS (for core >= 5.1)"
    lineinfile: dest=/opt/mapr/conf/env.sh regexp=^MAPR_LOGIN_OPTS= line="MAPR_LOGIN_OPTS=\"-Dhadoop.login=hybrid -Dhttps.protocols=TLSv1.2 ${MAPR_JAAS_CONFIG_OPTS} ${MAPR_ZOOKEEPER_OPTS}\""
    sudo: yes
    when: ((security == "kerberos") and (mapr_version >= 510))

  - name: Set MAPR_SUBNETS
    lineinfile: dest=/opt/mapr/conf/env.sh line="export MAPR_SUBNETS={{ my_ip.split('.')[:3] | join('.') }}.0/24"
    # lineinfile: dest=/opt/mapr/conf/env.sh line="export MAPR_SUBNETS={{ my_ip | ipsubnet(24) }}"
    # Above line requires python-netaddr to be installed
    when: set_mapr_subnets

  - name: Configure Classic Mode
    include: configure_classic.yml
    when: (hostname in packages_core.jobtracker.host) or (hostname in packages_core.tasktracker.host)

  - name: Configure YARN Mode
    include: configure_yarn.yml


    #####################
    ### HBase section ###
    #####################
  - name: env.sh -> replace MAPR_HBASE_CLIENT_OPTS
    lineinfile: dest=/opt/mapr/conf/env.sh regexp=MAPR_HBASE_CLIENT_OPTS= line="export MAPR_HBASE_CLIENT_OPTS=\"${HYBRID_LOGIN_OPTS}\""
    sudo: yes
    when: (security == "kerberos")
  - name: env.sh -> replace MAPR_HBASE_SERVER_OPTS
    lineinfile: dest=/opt/mapr/conf/env.sh regexp=MAPR_HBASE_SERVER_OPTS= line="export MAPR_HBASE_SERVER_OPTS=\"${KERBEROS_LOGIN_OPTS} ${MAPR_SSL_OPTS} -Dmapr.library.flatclass\""
    sudo: yes
    when: (security == "kerberos")

  - name: Configure Hbase
    include: configure_hbase.yml
    when: (hostname in packages_eco.hbase.host)


    ####################
    ### Hive section ###
    ####################
  - name: env.sh -> replace MAPR_HIVE_SERVER_LOGIN_OPTS
    lineinfile: dest=/opt/mapr/conf/env.sh regexp="MAPR_HIVE_SERVER_LOGIN_OPTS=\"-Dhadoop.login=maprsasl_keytab\"" line="  MAPR_HIVE_SERVER_LOGIN_OPTS=\"-Dhadoop.login=hybrid\""
    sudo: yes
    ignore_errors: true
    when: (security == "kerberos")
  - name: env.sh -> replace MAPR_HIVE_LOGIN_OPTS
    lineinfile: dest=/opt/mapr/conf/env.sh regexp="MAPR_HIVE_LOGIN_OPTS=\"-Dhadoop.login=maprsasl\"" line="  MAPR_HIVE_LOGIN_OPTS=\"-Dhadoop.login=hybrid\""
    sudo: yes
    ignore_errors: true
    when: (security == "kerberos")

  - name: Configure Hive
    include: configure_hive.yml
    when: (hostname in packages_eco.hive.host)


    ######################
    ### HttpFs section ###
    ######################
  - name: Configure HttpFs
    include: configure_httpfs.yml
    when: (hostname in packages_eco.httpfs.host)


    ###################
    ### Hue section ###
    ###################
  - name: Configure Hue
    include: configure_hue.yml
    when: (hostname in packages_eco.hue.host)


    ######################
    ### Impala section ###
    ######################
  - name: Configure Impala
    include: configure_impala.yml
    when: (hostname in packages_eco.impala.host)


    #####################
    ### Oozie section ###
    #####################
  - name: Configure Oozie
    include: configure_oozie.yml
    when: (hostname in packages_eco.oozie.host)


    #####################
    ### Sqoop section ###
    #####################
  - name: Find Sqoop config dir for Sqoop < 1.99.7
    shell: ls -d /opt/mapr/sqoop/sqoop-*/server/conf
    register: sqoop_conf_dir
    ignore_errors: true
  - name: Find Sqoop config dir for Sqoop >= 1.99.7
    shell: ls -d /opt/mapr/sqoop/sqoop-*/conf
    register: sqoop_conf_dir
    ignore_errors: true
    when: (sqoop_conf_dir.rc != 0)

  - name: Configure Sqoop2
    include: configure_sqoop.yml
    when: (hostname in packages_eco.sqoop2_server.host)


    #####################
    ### Spark section ###
    #####################
  - name: Configure Spark
    include: configure_spark.yml
    when: hostname in packages_eco.spark.host


    #####################
    ### Kafka section ###
    #####################
  - name: Configure Kafka
    include: configure_kafka.yml
    when: (hostname in packages_eco.kafka.host)


    ######################
    ### Sentry section ###
    ######################
  - name: Configure Sentry
    include: configure_sentry.yml
    when: (hostname in packages_eco.sentry.host)
  
  - name: Ensure that /opt/mapr/sentry/ exists
    command: "mkdir -p /opt/mapr/sentry/"
    when: packages_eco.sentry.host

  - name: Copy sentry-site.xml into /opt/mapr/sentry
    template: src=sentry/sentry-site.xml.{{security}} dest=/opt/mapr/sentry/sentry-site.xml
    when: packages_eco.sentry.host


    #####################
    ### Drill section ###
    #####################
  - name: Configure Drill
    include: configure_drill.yml
    when: (hostname in packages_eco.drill.host)
