# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2


    - name: Build and push Web images
      uses: docker/build-push-action@v2
      with:
        username: diptan
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        repository: diptan/web
        path: web

    - name: Build and push Trainer images
      uses: docker/build-push-action@v2
      with:
        username: diptan
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        repository: diptan/trainer
        path: trainer

    - name: Build and push Streamer images
      uses: docker/build-push-action@2
      with:
        username: diptan
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
        repository: diptan/streamer
        path: streamer
